# Generated by Django 4.2.7 on 2024-01-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbot',
            name='custom_task',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        # migrations.AlterField(
        #     model_name='taskbot',
        #     name='task_type',
        #     field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_column='task_type_id', default=list, null=True, size=None),
        # ),
        # migrations.CreateModel(
        #     name='SocialMediaMessage',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('message_text', models.TextField()),
        #         ('category', models.CharField(db_index=True, max_length=100)),
        #         ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=20)),
        #         ('metadata', models.JSONField(blank=True, default=dict)),
        #         ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
        #         ('message_hash', models.CharField(editable=False, max_length=32)),
        #         ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.socialmediaaccount')),
        #     ],
        #     options={
        #         'db_table': 'social_media_messages',
        #         'unique_together': {('account', 'message_hash')},
        #     },
        # ),
    ]
    
