# Generated by Django 5.1.7 on 2026-03-04 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_taskbot_custom_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'groups_info',
            },
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='group',
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='group',
            field=models.ManyToManyField(blank=True, db_table='social_media_account_groups', related_name='accounts', to='dashboard.groupsinfo'),
        ),
    ]
