# Generated by Django 5.1.7 on 2026-03-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_groupsinfo_remove_socialmediaaccount_group_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE social_media_account_groups
                        RENAME COLUMN socialmediaaccount_id TO account_id;

                        ALTER TABLE social_media_account_groups
                        RENAME COLUMN groupsinfo_id TO group_id;
                    """,
                    reverse_sql="""
                        ALTER TABLE social_media_account_groups
                        RENAME COLUMN account_id TO socialmediaaccount_id;

                        ALTER TABLE social_media_account_groups
                        RENAME COLUMN group_id TO groupsinfo_id;
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='SocialMediaAccountGroup',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        (
                            'account',
                            models.ForeignKey(
                                db_column='account_id',
                                on_delete=django.db.models.deletion.CASCADE,
                                to='dashboard.socialmediaaccount',
                            ),
                        ),
                        (
                            'group',
                            models.ForeignKey(
                                db_column='group_id',
                                on_delete=django.db.models.deletion.CASCADE,
                                to='dashboard.groupsinfo',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'social_media_account_groups',
                        'constraints': [
                            models.UniqueConstraint(
                                fields=('account', 'group'),
                                name='uq_socialmediaaccount_group',
                            ),
                        ],
                    },
                ),
            ],
        ),
    ]