# Generated by Django 5.1.7 on 2026-03-11 19:32

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_taskbot_task_type_socialmediaaccountgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='groups_to_search',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='socialmediaaccountgroup',
            name='growth',
            field=models.BooleanField(default=False),
        ),
    ]
