# Generated by Django 5.1.7 on 2026-03-13 16:53

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_socialmediaaccount_groups_to_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='proffesional_mode',
            field=models.BooleanField(default=False),
        ),

    ]
