# Generated by Django 5.1.7 on 2026-03-13 16:58

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_socialmediaaccount_proffesional_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediaaccount',
            old_name='proffesional_mode',
            new_name='professional_mode',
        ),
    ]
