# Generated by Django 5.1.7 on 2026-03-16 15:15

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

class CreateModelIfNotExists(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        existing_tables = set(schema_editor.connection.introspection.table_names())

        if table_name in existing_tables:
            # La tabla ya existe: no hace nada, pero la migración queda aplicada.
            return

        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        existing_tables = set(schema_editor.connection.introspection.table_names())

        if table_name not in existing_tables:
            return

        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_proffesional_mode_socialmediaaccount_professional_mode_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='socialmediaaccount',
        #     name='group',
        # ),
        # migrations.AlterField(
        #     model_name='taskbot',
        #     name='task_type',
        #     field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_column='task_type_id', default=list, null=True, size=None),
        # ),
        CreateModelIfNotExists(
            name='SocialMediaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(
                    choices=[('active', 'Active'), ('disabled', 'Disabled')],
                    db_index=True,
                    default='active',
                    max_length=20
                )),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('message_hash', models.CharField(editable=False, max_length=32)),
                (
                    'account',
                    models.ForeignKey(
                        db_column='account_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='dashboard.socialmediaaccount',
                    )
                ),
            ],
            options={
                'db_table': 'social_media_messages',
            },
        ),
        migrations.CreateModel(
            name='BlacklistAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(db_index=True, default='facebook', editable=False, max_length=20)),
                ('external_account_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('matched_layers', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blacklist_accounts',
                'indexes': [models.Index(fields=['platform'], name='blacklist_a_platfor_33064f_idx'), models.Index(fields=['external_account_id'], name='blacklist_a_externa_0570b9_idx'), models.Index(fields=['account_name'], name='blacklist_a_account_1ec326_idx'), models.Index(fields=['created_at'], name='blacklist_a_created_50968d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(db_index=True, default='facebook', editable=False, max_length=20)),
                ('external_account_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_key', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source_hashtag', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('COMMENTED', 'Commented'), ('NO_RESPONSE', 'No Response'), ('RESPONDED', 'Responded'), ('REQUESTED_DATA', 'Requested Data'), ('REQUESTED_QUOTE', 'Requested Quote'), ('ALERTED', 'Alerted'), ('BLACKLISTED', 'Blacklisted')], db_index=True, default='NEW', max_length=30)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('first_commented_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_at', models.DateTimeField(blank=True, null=True)),
                ('last_alert_at', models.DateTimeField(blank=True, null=True)),
                ('competitor_score', models.PositiveIntegerField(default=0)),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False)),
                ('blacklist_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered_by_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_prospects', to='dashboard.socialmediaaccount')),
            ],
            options={
                'db_table': 'prospects',
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(choices=[('DATA_REQUEST', 'Data Request'), ('QUOTE_REQUEST', 'Quote Request')], db_index=True, max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High')], db_index=True, default='NORMAL', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('email_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_alerts', to='dashboard.socialmediaaccount')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.prospect')),
            ],
            options={
                'db_table': 'alerts_log',
            },
        ),
        migrations.CreateModel(
            name='ProspectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_post_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('post_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('post_text', models.TextField(blank=True, null=True)),
                ('post_published_at', models.DateTimeField(blank=True, null=True)),
                ('matched_hashtag', models.CharField(blank=True, max_length=255, null=True)),
                ('used_for_intro_comment', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dashboard.prospect')),
            ],
            options={
                'db_table': 'prospect_posts',
            },
        ),
        migrations.CreateModel(
            name='ProspectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_comment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('actor_type', models.CharField(choices=[('BOT', 'Bot'), ('PROSPECT', 'Prospect'), ('HUMAN', 'Human')], db_index=True, max_length=20)),
                ('comment_kind', models.CharField(choices=[('INTRO', 'Intro'), ('AUTO_REPLY_DATA', 'Auto Reply Data'), ('AUTO_REPLY_QUOTE', 'Auto Reply Quote'), ('FOLLOW_UP', 'Follow Up'), ('HUMAN_REPLY', 'Human Reply'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('template_id', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_comments', to='dashboard.socialmediaaccount')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.prospect')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='dashboard.prospectpost')),
            ],
            options={
                'db_table': 'prospect_comments',
            },
        ),
        migrations.CreateModel(
            name='ProspectReplyClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('REQUESTED_DATA', 'Requested Data'), ('REQUESTED_QUOTE', 'Requested Quote'), ('POSITIVE', 'Positive'), ('AMBIGUOUS', 'Ambiguous'), ('IGNORE', 'Ignore')], db_index=True, max_length=30)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('decision_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='dashboard.prospectcomment')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='dashboard.prospect')),
            ],
            options={
                'db_table': 'prospect_reply_classifications',
            },
        ),
        migrations.CreateModel(
            name='QuoteAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_type_of_cleaning', models.TextField(blank=True, null=True)),
                ('q2_space_size', models.TextField(blank=True, null=True)),
                ('q3_needed_date', models.TextField(blank=True, null=True)),
                ('q4_condition', models.TextField(blank=True, null=True)),
                ('min_answers_ready_for_alert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_answer', to='dashboard.prospect')),
            ],
            options={
                'db_table': 'quote_answers',
            },
        ),
        
        migrations.AddField(
            model_name='prospectcomment',
            name='related_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_comments', to='dashboard.socialmediamessage'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['platform'], name='prospects_platfor_3f52ee_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['status'], name='prospects_status_a22ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['is_blacklisted'], name='prospects_is_blac_ba40df_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['account_name'], name='prospects_account_85ca81_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['created_at'], name='prospects_created_4e96ff_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['event_code'], name='alerts_log_event_c_a7b8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['priority'], name='alerts_log_priorit_0ecbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['sent_at'], name='alerts_log_sent_at_84b504_idx'),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['created_at'], name='alerts_log_created_2c0d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectpost',
            index=models.Index(fields=['external_post_id'], name='prospect_po_externa_6604e7_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectpost',
            index=models.Index(fields=['used_for_intro_comment'], name='prospect_po_used_fo_cd5b48_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectpost',
            index=models.Index(fields=['created_at'], name='prospect_po_created_035d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectreplyclassification',
            index=models.Index(fields=['intent'], name='prospect_re_intent_5d2924_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectreplyclassification',
            index=models.Index(fields=['created_at'], name='prospect_re_created_ca6279_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediamessage',
            unique_together={('account', 'message_hash')},
        ),
        migrations.AddIndex(
            model_name='prospectcomment',
            index=models.Index(fields=['platform_comment_id'], name='prospect_co_platfor_56184e_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectcomment',
            index=models.Index(fields=['actor_type'], name='prospect_co_actor_t_a68e82_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectcomment',
            index=models.Index(fields=['comment_kind'], name='prospect_co_comment_f29841_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectcomment',
            index=models.Index(fields=['sent_at'], name='prospect_co_sent_at_61a191_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectcomment',
            index=models.Index(fields=['created_at'], name='prospect_co_created_82bbbc_idx'),
        ),
    ]
