# Generated by Django 5.1.7 on 2026-03-19 21:27

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_socialmediaaccount_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('campaign_info', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('alt_phone_number', models.CharField(max_length=255)),
                ('webpage_url', models.TextField()),
                ('fanpage_url', models.TextField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'campaign_info',
            },
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='campaign_info_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.campaigninfo'),
        ),
    ]
