# Generated by Django 5.1.7 on 2026-03-19 21:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_campaigninfo_remove_socialmediaaccount_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediaaccount',
            old_name='campaign_info_id',
            new_name='campaign_info',
        ),
    ]
