# Generated by Django 5.1.7 on 2026-03-25 21:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_campaign_info_id_socialmediaaccount_campaign_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedForRecommendationOrReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.BooleanField(default=False)),
                ('mention', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.socialmediaaccount')),
            ],
            options={
                'db_table': 'used_for_recommendation_or_review',
                'constraints': [models.UniqueConstraint(fields=('account',), name='unique_used_for_recommendation_or_review_account')],
            },
        ),
    ]
