# Generated by Django 5.1.7 on 2026-03-31 17:35

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_socialmediaaccount_group_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='socialmediaaccount',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
